### ISSUE TITLE
When hash folder does not exist, the result file is not created 

### ISSUE THREAD

**Issue by xhajnal** [xhajnal/video_bees#49]
```
SAVE TRACES AS CSV
Traceback (most recent call last):
  File "D:/Git/video_bees/src/dave.py", line 1587, in <module>
    run_both()
  File "D:/Git/video_bees/src/dave.py", line 7, in run_both
    run(is_first_run=False)
  File "D:/Git/video_bees/src/dave.py", line 36, in run
    analyse('../data/Video_tracking/190822/20190822_111607344_1BEE_generated_20210430_080914_nn.csv', 1, is_first_run=a)
  File "D:\Git\video_bees\src\analyse.py", line 710, in analyse
    save_traces_as_csv(all_final_traces, os.path.basename(csv_file_path), silent=silent, debug=debug, is_first_run=is_first_run, overwrite_file=overwrite_file)
  File "D:\Git\video_bees\src\dave_io.py", line 567, in save_traces_as_csv
    with open(file_path, "w") as file:
FileNotFoundError: [Errno 2] No such file or directory: '../output/traces/6619924870081120246/20190822_111607344_1BEE_generated_20210430_080914_nn.csv'
```

**Comment by xhajnal** [comment]
fixed in 0f756057a62000c2dcf119355b2daccc7d1d704b
